FROM ghcr.io/seisscoped/container-base:centos7

LABEL maintainer="Yiyu Ni"

RUN  cd /home/scoped \
    && pip install git+https://github.com/qibinshi/TeleseismicDenoiser.git \
    && git pull \
    && docker-clean